### ISSUE TITLE
Failed to connect with rtsp://127.0.0.1:8554/test

### ISSUE THREAD

**Issue by agonsalihu** [D-Y-Innovations/gst-rtsp-server-android-demo#2]
Hi,

I cloned your repo and build it in Android 8.1 with success, but when I run on terminal with vlc rtsp://127.0.0.1:8554/test. I get some errors. 

![Screenshot from 2020-07-23 18-07-45](https://user-images.githubusercontent.com/43940623/88310024-7cc96b80-cd0f-11ea-9f82-5534e992675c.png)

I would appreciate it if you could give me some advice about fixing this or explaining.

**Comment by hexray-newbee** [comment]
127.0.0.1 is loopback IP. Replace it with the Android IP.

**Comment by ranjanZ** [comment]
Facing the same issue
